apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: argocd
    interval: 30s
    rules:
    # Alert when application is unhealthy
    - alert: ArgoCDAppUnhealthy
      expr: |
        argocd_app_info{health_status!="Healthy"} > 0
      for: 5m
      labels:
        severity: warning
        component: argocd
      annotations:
        summary: "ArgoCD Application {{ $labels.name }} is unhealthy"
        description: "Application {{ $labels.name }} in namespace {{ $labels.dest_namespace }} has been unhealthy for more than 5 minutes. Current status: {{ $labels.health_status }}"
    
    # Alert when application is out of sync
    - alert: ArgoCDAppOutOfSync
      expr: |
        argocd_app_info{sync_status="OutOfSync"} > 0
      for: 10m
      labels:
        severity: info
        component: argocd
      annotations:
        summary: "ArgoCD Application {{ $labels.name }} is out of sync"
        description: "Application {{ $labels.name }} has been out of sync for more than 10 minutes."
    
    # Alert when sync fails
    - alert: ArgoCDSyncFailed
      expr: |
        increase(argocd_app_sync_total{phase="Failed"}[5m]) > 0
      labels:
        severity: warning
        component: argocd
      annotations:
        summary: "ArgoCD sync failed for {{ $labels.name }}"
        description: "Sync operation failed for application {{ $labels.name }}"
    
    # Alert when repo server is down
    - alert: ArgoCDRepoServerDown
      expr: |
        up{job="argocd-repo-server-metrics"} == 0
      for: 2m
      labels:
        severity: critical
        component: argocd
      annotations:
        summary: "ArgoCD Repo Server is down"
        description: "ArgoCD repo server has been down for more than 2 minutes"
    
    # Alert on high sync duration
    - alert: ArgoCDHighSyncDuration
      expr: |
        histogram_quantile(0.95, rate(argocd_app_sync_bucket[5m])) > 300
      for: 5m
      labels:
        severity: warning
        component: argocd
      annotations:
        summary: "ArgoCD sync taking too long"
        description: "95th percentile of sync duration is above 5 minutes"
